services:
  catalog-db:
    image: postgres:16-alpine
    container_name: catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_DB: ${CATALOG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - order-flow-net

  notification-db:
    image: postgres:16-alpine
    container_name: notification_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - order-flow-net

  order-db:
    image: postgres:16-alpine
    container_name: order_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - order-flow-net

  user-db:
    image: postgres:16-alpine
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - order-flow-net

  catalog-service:
    build: ./catalog-service
    container_name: catalog_service
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=catalog-db
      - DB_PORT=5432
      - DB_USER=${CATALOG_DB_USER}
      - DB_PASSWORD=${CATALOG_DB_PASSWORD}
      - DB_NAME=${CATALOG_DB_NAME}
    depends_on:
      catalog-db:
        condition: service_healthy
    networks:
      - order-flow-net
  
  notification-service:
    build: ./notification-service
    container_name: notification_service
    restart: unless-stopped
    ports:
      - "50052:50052"
    environment:
      - DB_HOST=notification-db
      - DB_PORT=5432
      - DB_USER=${NOTIFICATION_DB_USER}
      - DB_PASSWORD=${NOTIFICATION_DB_PASSWORD}
      - DB_NAME=${NOTIFICATION_DB_NAME}
    depends_on:
      notification-db:
        condition: service_healthy
    networks:
      - order-flow-net
  
  order-service:
    build: ./order-service
    container_name: order_service
    restart: unless-stopped
    ports:
      - "50053:50053"
    environment:
      - DB_HOST=order-db
      - DB_PORT=5432
      - DB_USER=${ORDER_DB_USER}
      - DB_PASSWORD=${ORDER_DB_PASSWORD}
      - DB_NAME=${ORDER_DB_NAME}
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - order-flow-net

  user-service:
    build: ./user-service
    container_name: user_service
    restart: unless-stopped
    ports:
      - "50054:50054"
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - order-flow-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - order-flow-net

volumes:
  catalog_pgdata:
  notification_pgdata:
  order_pgdata:
  user_pgdata:
  rabbitmq_data:


networks:
  order-flow-net:
    driver: bridge